version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: expense-tracker-backend
    ports:
      - "3000:3000"
    networks:
      - expense-tracker-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: expense-tracker-frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
    networks:
      - expense-tracker-net

networks:
  expense-tracker-net:
    driver: bridge
